---
- name: create /etc/systemd/system/firewalld.service.d
  file: state=directory dest=/etc/systemd/system/firewalld.service.d

- name: put /etc/systemd/system/firewalld.service.d/docker.conf
  template: src=docker.conf dest=/etc/systemd/system/firewalld.service.d/docker.conf

- name: install firewalld
  apt: name=firewalld
  when: ansible_os_family == 'Debian'

- name: apply firewalld rules
  shell: firewall-cmd --add-port={{ item }}
  with_items: "{{ firewalld.open_ports }}"

- name: apply firewalld rules permanently
  shell: firewall-cmd --add-port={{ item }} --permanent
  with_items: "{{ firewalld.open_ports }}"

- name: add open ports to external zone
  shell: firewall-cmd --zone=external --add-port={{ item }}
  with_items: "{{ firewalld.open_ports }}"

- name: add open ports to external zone permanently
  shell: firewall-cmd --zone=external --add-port={{ item }} --permanent
  with_items: "{{ firewalld.open_ports }}"

- name: add trusted interfaces to a trusted zone
  shell: firewall-cmd --zone=trusted --add-interface={{ item }}
  with_items: "{{ firewalld.trusted_interfaces }}"

- name: add trusted interfaces to a trusted zone permanently
  shell: firewall-cmd --zone=trusted --add-interface={{ item }} --permanent
  with_items: "{{ firewalld.trusted_interfaces }}"

- name: create masquerading rule in certain zones
  shell: firewall-cmd --zone={{ item }} --add-masquerade
  with_items: "{{ firewalld.masq_zones }}"

- name: create masquerading rule in certain zones permanently
  shell: firewall-cmd --zone={{ item }} --add-masquerade --permanent
  with_items: "{{ firewalld.masq_zones }}"

- name: add external interfaces to an external zone
  shell: firewall-cmd --zone=external --add-interface={{ item }}
  with_items: "{{ firewalld.external_interfaces }}"

- name: add external interfaces to an external zone permanently
  shell: firewall-cmd --zone=external --add-interface={{ item }} --permanent
  with_items: "{{ firewalld.external_interfaces }}"

- name: add port forwarding rules to an external zone
  shell: firewall-cmd --zone=external --add-forward-port=port={{ item.port }}:proto={{ item.proto }}:toport={{ item.toport }}:toaddr={{ item.toaddr }}
  with_items: "{{ firewalld.forwarded_ports }}"

- name: add port forwarding rules to an external zone permanently
  shell: firewall-cmd --zone=external --add-forward-port=port={{ item.port }}:proto={{ item.proto }}:toport={{ item.toport }}:toaddr={{ item.toaddr }} --permanent
  with_items: "{{ firewalld.forwarded_ports }}"

- name: add rich rules to an external zone
  shell: firewall-cmd --zone=external --add-rich-rule='{{ item.rule }}'
  with_items: "{{ firewalld.rich_rules }}"

- name: add rich rules to an external zone permanently
  shell: firewall-cmd --zone=external --add-rich-rule='{{ item.rule }}' --permanent
  with_items: "{{ firewalld.rich_rules }}"

- name: add direct rules
  shell: firewall-cmd --direct --add-rule ipv4 {{ item.table }} {{ item.chain }} {{ item.priority }} {{ item.args }}
  with_items: "{{ firewalld.direct_rules }}"

- name: add direct rules permanently
  shell: firewall-cmd --direct --add-rule ipv4 {{ item.table }} {{ item.chain }} {{ item.priority }} {{ item.args }} --permanent
  with_items: "{{ firewalld.direct_rules }}"
